import React from 'react';
import {
  User,
  CaretLeft,
  ArrowUp,
  ArrowDown,
  ChartLineUp,
  CheckCircle,
  Check,
  XCircle,
  X,
  Pulse,
  TrendUp,
  FirstAid,
  Warning,
  CaretUp,
  CaretDown,
  Bell,
  Info,
  Clock,
  PlusCircle,
  Drop,
  Circle,
  Heart,
  Gauge,
  Flask,
  FunnelSimple,
  Minus,
  WarningCircle,
  Eye,
  EyeSlash,
  Target,
  Article,
  Receipt,
  UsersThree,
  Calendar,
  PencilSimple,
  FastForwardCircle,
  Pill,
  Lightbulb,
  SquaresFour,
  DotsThreeVertical,
  MagnifyingGlass,
  Trophy,
  ChatCircleDots,
  ShareNetwork,
  Trash,
  BookmarkSimple,
  Activity,
  Brain,
  ForkKnife,
  Moon,
  Flag,
  Rocket,
  Stars,
  Smiley,
  Plus,
  CaretRight,
  EnvelopeSimple,
  CloudArrowUp,
  SignOut,
  SpeakerHigh,
  DeviceMobile,
  Robot,
  Bicycle,
  BowlSteam
} from 'phosphor-react-native';

// Map common Ionicons names used in the app to Phosphor components
const ionToPhosphor = {
  'chevron-back': CaretLeft,
  'arrow-back': CaretLeft,
  'stats-chart': ChartLineUp,
  'stats-chart-outline': ChartLineUp,
  'checkmark-circle': CheckCircle,
  'checkmark': Check,
  'close-circle': XCircle,
  'close': X,
  'pulse': Pulse,
  'trending-up': TrendUp,
  'medical': FirstAid,
  'medkit-outline': FirstAid,
  'medical-outline': FirstAid,
  'warning': Warning,
  'warning-outline': WarningCircle,
  'alert-circle': WarningCircle,
  'alert-circle-outline': WarningCircle,
  'chevron-up': CaretUp,
  'chevron-down': CaretDown,
  'notifications': Bell,
  'information-circle': Info,
  'time-outline': Clock,
  'time': Clock,
  'alarm-outline': Clock,
  'alarm': Clock,
  'add-circle': PlusCircle,
  'add-circle-outline': PlusCircle,
  'person-outline': User,
  'person': User,
  'water': Drop,
  'ellipse-outline': Circle,
  'heart-outline': Heart,
  'heart': Heart,
  'speedometer-outline': Gauge,
  'speedometer': Gauge,
  'pulse-outline': Pulse,
  'flask-outline': Flask,
  'filter': FunnelSimple,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'remove': Minus,
  'eye': Eye,
  'eye-off': EyeSlash,
  'target':Target,
  'article':Article,
  'community':UsersThree,
  'calendar':Calendar,
  'calendar-outline':Calendar,
  'pill':Pill,
  'edit-2':PencilSimple,
  'skip-forward':FastForwardCircle,
  // Blog specific
  'apps-outline': SquaresFour,
  'bulb-outline': Lightbulb,
  'bulb': Lightbulb,
  'trophy-outline': Trophy,
  'chatbubbles-outline': ChatCircleDots,
  'ellipsis-vertical': DotsThreeVertical,
  'create-outline': PencilSimple,
  'trash-outline': Trash,
  'trash': Trash,
  'bookmark': BookmarkSimple,
  'bookmark-outline': BookmarkSimple,
  'share-outline': ShareNetwork,
  'analytics-outline': ChartLineUp,
  'analytics': ChartLineUp,
  // Goal tracker specific
  'fitness-outline': Bicycle,
  'brain-outline': Brain,
  'nutrition-outline': ForkKnife,
  'moon-outline': Moon,
  'people-outline': UsersThree,
  'flag-outline': Flag,
  'rocket-outline': Rocket,
  'sparkles-outline': Robot,
  'happy-outline': Smiley,
  'restaurant-outline':BowlSteam,
  'add': Plus,
  // Profile screen specific
  'chevron-forward': CaretRight,
  'trophy': Trophy,
  'mail': EnvelopeSimple,
  'cloud-upload': CloudArrowUp,
  'log-out': SignOut,
  'people': UsersThree,
  'create': PencilSimple,
  // Reminders screen specific
  'volume-high': SpeakerHigh,
  'phone-portrait': DeviceMobile,
  
};

const Fallback = Info;

export default function Icon({ name, size = 24, color = '#000', weight = 'regular', ...rest }) {
  const Component = ionToPhosphor[name] || Fallback;
  return <Component size={size} color={color} weight={weight} {...rest} />;
}
